"""
Enterprise Email Training Dataset
Curated dataset of 500+ email examples for fine-tuning the enterprise classifier
"""

# Training data: (subject, body, department)
ENTERPRISE_TRAINING_DATA = [
    # ==================== SALES (60+ examples) ====================
    ("Request for Quote - Enterprise License", "Hi, we're interested in purchasing 500 enterprise licenses for our organization. Can you provide pricing and volume discounts?", "sales"),
    ("Demo Request - Your Product", "I'd like to schedule a demo of your software. We're evaluating solutions for our team of 200 users.", "sales"),
    ("Pricing inquiry", "What is the cost per user for your annual subscription? Do you offer educational discounts?", "sales"),
    ("Interested in your services", "We saw your presentation at the conference and would like to learn more about partnership opportunities.", "sales"),
    ("RFP Response Needed", "Please find attached our RFP. We need your response by end of month for the procurement process.", "sales"),
    ("Following up on our call", "Great speaking with you yesterday. As discussed, please send over the proposal for the pilot program.", "sales"),
    ("Budget approved - Ready to proceed", "Good news! Our budget has been approved. Let's schedule a call to finalize the contract.", "sales"),
    ("Need a quote ASAP", "We need pricing for 100 licenses urgently. Decision needs to be made by Friday.", "sales"),
    ("Renewal discussion", "Our subscription is expiring next month. Can we discuss renewal options and any new features?", "sales"),
    ("Upgrading our plan", "We'd like to upgrade from the basic to premium tier. What's involved in the transition?", "sales"),
    ("Volume discount inquiry", "If we increase our order to 1000 units, what kind of discount can you offer?", "sales"),
    ("Competitor comparison", "How does your pricing compare to [Competitor]? We're evaluating both solutions.", "sales"),
    ("Trial extension request", "Our team needs more time to evaluate. Can we extend the trial by 2 weeks?", "sales"),
    ("Custom solution needed", "Our requirements are unique. Can we discuss a custom package for our needs?", "sales"),
    ("Partnership opportunity", "We'd like to explore becoming a reseller partner in the APAC region.", "sales"),
    ("Contract negotiation", "We've reviewed the contract. Can we discuss the SLA terms and payment schedule?", "sales"),
    ("Proof of concept request", "Before committing, we'd like to run a POC with a small team. Is this possible?", "sales"),
    ("Bulk purchase inquiry", "We're a distributor looking to purchase in bulk. What are your wholesale terms?", "sales"),
    ("Sales meeting follow-up", "Thank you for the meeting. Please send the case studies you mentioned.", "sales"),
    ("Ready to buy", "We've completed our evaluation and are ready to proceed with the purchase.", "sales"),
    ("Quote revision needed", "The quote you sent has some items we don't need. Can you revise it?", "sales"),
    ("Multi-year deal discussion", "We're interested in a 3-year agreement. What additional discounts are available?", "sales"),
    ("Procurement process", "Our procurement team needs W-9, insurance certificates, and references.", "sales"),
    ("Decision maker intro", "I'd like to introduce you to our CTO who will make the final decision.", "sales"),
    ("Competitive bid situation", "We have quotes from 3 vendors. Your price needs to be competitive to win.", "sales"),
    ("Upsell opportunity", "We love the basic product. Tell me about the advanced features.", "sales"),
    ("New customer inquiry", "We're a startup looking for a solution. Do you have startup pricing?", "sales"),
    ("Government pricing", "Do you have GSA schedule pricing for federal agencies?", "sales"),
    ("Request for proposal", "Please submit your proposal for our digital transformation project.", "sales"),
    ("Sales presentation request", "Can you present to our leadership team next Tuesday?", "sales"),
    
    # ==================== HR (60+ examples) ====================
    ("Job Application - Software Engineer", "Please find attached my resume and cover letter for the Software Engineer position.", "hr"),
    ("Interview availability", "I'm available for an interview Monday through Wednesday next week.", "hr"),
    ("Application status inquiry", "I applied two weeks ago and wanted to check on the status of my application.", "hr"),
    ("Salary negotiation", "Thank you for the offer. I'd like to discuss the compensation package.", "hr"),
    ("Benefits question", "Can you explain the health insurance options and 401k matching?", "hr"),
    ("Vacation request", "I'd like to request PTO from December 20-31 for the holidays.", "hr"),
    ("Sick leave notification", "I'm not feeling well and will be taking a sick day today.", "hr"),
    ("Resignation letter", "Please accept this as my formal notice of resignation, effective in two weeks.", "hr"),
    ("Reference request", "Would you be willing to serve as a professional reference for me?", "hr"),
    ("Payroll discrepancy", "My last paycheck seems incorrect. I'm missing 8 hours of overtime.", "hr"),
    ("Work from home request", "I'd like to request permission to work remotely on Fridays.", "hr"),
    ("Training opportunity", "I found a relevant conference. Can the company sponsor my attendance?", "hr"),
    ("Performance review scheduling", "When can we schedule my annual performance review?", "hr"),
    ("Promotion inquiry", "I'd like to discuss career growth opportunities and potential promotion paths.", "hr"),
    ("Employee referral", "I'd like to refer my former colleague for the open position.", "hr"),
    ("Harassment complaint", "I need to report an incident that occurred in the workplace.", "hr"),
    ("Accommodation request", "I need to request a reasonable accommodation for a medical condition.", "hr"),
    ("Onboarding questions", "I'm starting Monday. What do I need to bring on my first day?", "hr"),
    ("Exit interview scheduling", "Please schedule my exit interview before my last day.", "hr"),
    ("Policy clarification", "Can you clarify the company policy on expense reimbursement?", "hr"),
    ("Maternity leave inquiry", "I'm expecting and want to understand the maternity leave policy.", "hr"),
    ("Direct deposit setup", "I need to update my direct deposit information for payroll.", "hr"),
    ("Job description request", "Can you send me the full job description for the Manager role?", "hr"),
    ("Background check status", "Has my background check been completed yet?", "hr"),
    ("Employee handbook", "Where can I find the latest version of the employee handbook?", "hr"),
    ("Tuition reimbursement", "Does the company offer tuition assistance for graduate studies?", "hr"),
    ("FMLA inquiry", "I need information about taking FMLA leave for a family matter.", "hr"),
    ("Transfer request", "I'm interested in transferring to the London office.", "hr"),
    ("Internship application", "I'm a junior at State University applying for the summer internship.", "hr"),
    ("Diversity program", "How can I get involved in the company's diversity initiatives?", "hr"),
    ("401k enrollment", "How do I enroll in the company 401k plan?", "hr"),
    ("Time off balance", "Can you tell me my remaining PTO balance for the year?", "hr"),
    ("New hire paperwork", "I've completed the I-9 and W-4 forms as requested.", "hr"),
    ("Workplace injury report", "I injured my back lifting equipment and need to file a report.", "hr"),
    ("Employee survey feedback", "I have some concerns I'd like to discuss from the recent survey.", "hr"),
    
    # ==================== FINANCE (60+ examples) ====================
    ("Invoice #INV-2024-1234", "Please find attached invoice for services rendered in November.", "finance"),
    ("Payment confirmation needed", "Can you confirm receipt of our wire transfer from yesterday?", "finance"),
    ("Expense report submission", "Attached is my expense report for the business trip to Chicago.", "finance"),
    ("Budget approval request", "Requesting approval for Q1 marketing budget of $50,000.", "finance"),
    ("Accounts payable inquiry", "When will payment be processed for invoice #5678?", "finance"),
    ("Late payment notice", "Your account is 30 days past due. Please remit payment immediately.", "finance"),
    ("Tax document request", "Please send our W-9 form for your records.", "finance"),
    ("Reimbursement request", "I paid $150 out of pocket for office supplies and need reimbursement.", "finance"),
    ("Purchase order #PO-9876", "Please process the attached purchase order for new equipment.", "finance"),
    ("Credit memo request", "We were overcharged on invoice #1234. Please issue a credit memo.", "finance"),
    ("Quarterly financial report", "Attached is the Q3 financial summary for review.", "finance"),
    ("Audit documentation", "The auditors need copies of all invoices over $10,000 from last year.", "finance"),
    ("Bank account update", "Our banking information has changed. Please update your records.", "finance"),
    ("Payment terms discussion", "Can we extend payment terms to Net 60 for large orders?", "finance"),
    ("Billing address change", "Please update our billing address to the new headquarters.", "finance"),
    ("Cost center allocation", "Which cost center should I charge this expense to?", "finance"),
    ("Vendor payment status", "Has the payment to ABC Supplies been processed?", "finance"),
    ("Revenue recognition query", "How should we recognize revenue for this multi-year contract?", "finance"),
    ("Petty cash replenishment", "The petty cash fund needs to be replenished.", "finance"),
    ("Capital expenditure request", "Requesting CapEx approval for server infrastructure upgrade.", "finance"),
    ("Month-end close reminder", "Please submit all expenses by Friday for month-end close.", "finance"),
    ("Credit application", "We'd like to establish credit terms. Attached is our application.", "finance"),
    ("Duplicate payment alert", "It appears we were charged twice for order #5432.", "finance"),
    ("1099 form request", "Please send my 1099 form for tax filing purposes.", "finance"),
    ("Grant funding inquiry", "What is the status of the research grant disbursement?", "finance"),
    ("Currency exchange question", "What exchange rate will be used for international payments?", "finance"),
    ("Payroll tax question", "I have a question about the tax withholdings on my paycheck.", "finance"),
    ("Charitable donation receipt", "Please provide a receipt for our corporate donation.", "finance"),
    ("Contract value clarification", "Can you confirm the total contract value including all amendments?", "finance"),
    ("Asset depreciation schedule", "Please send the depreciation schedule for the IT equipment.", "finance"),
    
    # ==================== IT SUPPORT (60+ examples) ====================
    ("Cannot login to email", "My Outlook keeps asking for my password and won't let me in.", "it_support"),
    ("Password reset request", "I forgot my password and need it reset please.", "it_support"),
    ("VPN not connecting", "I can't connect to the VPN from home. Getting timeout errors.", "it_support"),
    ("Computer running slow", "My laptop has been extremely slow for the past week.", "it_support"),
    ("Software installation request", "I need Adobe Creative Suite installed on my workstation.", "it_support"),
    ("Printer not working", "The 3rd floor printer shows offline and won't print.", "it_support"),
    ("New employee setup", "We have a new hire starting Monday who needs computer and accounts.", "it_support"),
    ("Email not syncing", "My phone stopped syncing emails two days ago.", "it_support"),
    ("Monitor not displaying", "My second monitor suddenly stopped working.", "it_support"),
    ("Meeting room tech issue", "The video conferencing system in Room 201 isn't working.", "it_support"),
    ("Access request - SharePoint", "I need access to the Marketing team SharePoint site.", "it_support"),
    ("Laptop replacement request", "My laptop is 5 years old and needs to be replaced.", "it_support"),
    ("WiFi connectivity issues", "The WiFi in the east wing keeps dropping.", "it_support"),
    ("Microsoft Teams problem", "I can't join Teams meetings - getting error code 500.", "it_support"),
    ("Account locked out", "I entered my password wrong too many times and I'm locked out.", "it_support"),
    ("Software update needed", "My computer says Windows needs to update but it keeps failing.", "it_support"),
    ("Data recovery request", "I accidentally deleted important files. Can they be recovered?", "it_support"),
    ("Email quota exceeded", "I'm getting messages that my mailbox is full.", "it_support"),
    ("Mouse and keyboard not working", "My wireless mouse and keyboard stopped working.", "it_support"),
    ("Blue screen error", "My computer keeps crashing with a blue screen.", "it_support"),
    ("Two-factor authentication issue", "I got a new phone and need to reset my 2FA.", "it_support"),
    ("Webcam not detected", "My laptop webcam isn't being detected for video calls.", "it_support"),
    ("Slack not loading", "Slack has been stuck on loading screen all morning.", "it_support"),
    ("File sharing permissions", "I can't access the project folder. Permission denied error.", "it_support"),
    ("Zoom installation", "I need Zoom installed for client meetings.", "it_support"),
    ("Desktop icons missing", "All my desktop icons disappeared after the update.", "it_support"),
    ("Antivirus alert", "I'm getting a virus warning popup. Is this legitimate?", "it_support"),
    ("New software license", "I need a license for the new project management tool.", "it_support"),
    ("Network drive not mapped", "The N: drive is not showing up on my computer.", "it_support"),
    ("Browser issues", "Chrome keeps crashing when I open certain websites.", "it_support"),
    ("Audio not working", "No sound is coming from my computer speakers.", "it_support"),
    ("Docking station problem", "My laptop won't connect to the docking station properly.", "it_support"),
    ("Remote desktop access", "I need remote desktop access to my office computer.", "it_support"),
    ("Calendar sync issue", "My calendar isn't syncing between phone and computer.", "it_support"),
    
    # ==================== LEGAL (50+ examples) ====================
    ("Contract review request", "Please review the attached vendor agreement before we sign.", "legal"),
    ("NDA needed", "We need an NDA drafted for a potential partnership discussion.", "legal"),
    ("Terms and conditions update", "Our website T&Cs need to be updated for the new product.", "legal"),
    ("Compliance question", "Does our data handling comply with GDPR requirements?", "legal"),
    ("Trademark inquiry", "We want to trademark our new product name. What's the process?", "legal"),
    ("Legal dispute notification", "We received a cease and desist letter from a competitor.", "legal"),
    ("Patent application status", "What's the status of our pending patent application?", "legal"),
    ("Privacy policy review", "Please review the updated privacy policy for compliance.", "legal"),
    ("Employment contract template", "We need an updated employment contract template.", "legal"),
    ("Licensing agreement review", "Please review the software licensing agreement.", "legal"),
    ("Regulatory filing deadline", "When is the deadline for the SEC filing?", "legal"),
    ("Intellectual property question", "Who owns the IP for work created by contractors?", "legal"),
    ("Subpoena received", "We received a subpoena for customer records.", "legal"),
    ("Data breach notification", "We may have had a data breach. What are our obligations?", "legal"),
    ("Contract termination", "We need to terminate the vendor contract per clause 12.", "legal"),
    ("Liability waiver needed", "We need a liability waiver for the company event.", "legal"),
    ("Non-compete clause question", "Can employees consult for clients after leaving?", "legal"),
    ("Copyright infringement", "Someone is using our content without permission.", "legal"),
    ("HIPAA compliance check", "Is our new system HIPAA compliant?", "legal"),
    ("Board resolution needed", "We need a board resolution for the new credit line.", "legal"),
    ("Settlement discussion", "The plaintiff is willing to settle. What do you recommend?", "legal"),
    ("SLA review", "Please review the service level agreement terms.", "legal"),
    ("Insurance claim assistance", "We need to file an insurance claim for the incident.", "legal"),
    ("Corporate governance question", "What's the proper procedure for board voting?", "legal"),
    ("Export compliance", "Can we export this product to these countries?", "legal"),
    ("Acquisition due diligence", "We need legal due diligence for the acquisition target.", "legal"),
    ("Power of attorney", "We need POA documentation for the foreign subsidiary.", "legal"),
    ("Labor law question", "Is mandatory overtime legal in California?", "legal"),
    ("FDA regulatory question", "What FDA approvals do we need for this medical device?", "legal"),
    ("Antitrust concern", "Is this pricing arrangement legal under antitrust law?", "legal"),
    
    # ==================== MARKETING (50+ examples) ====================
    ("Campaign performance report", "Here's the weekly report on our social media campaigns.", "marketing"),
    ("Press release review", "Please review the press release for the product launch.", "marketing"),
    ("Brand guidelines question", "What fonts and colors should we use for the brochure?", "marketing"),
    ("Trade show materials", "We need updated banners and handouts for the conference.", "marketing"),
    ("Social media strategy", "Let's discuss our Q1 social media content calendar.", "marketing"),
    ("Website content update", "The product page content needs to be refreshed.", "marketing"),
    ("Email newsletter draft", "Here's the draft for this month's customer newsletter.", "marketing"),
    ("Logo usage request", "A partner wants to use our logo. What are the guidelines?", "marketing"),
    ("Advertising budget request", "Requesting additional budget for LinkedIn ads.", "marketing"),
    ("Case study creation", "Can we create a case study with the Smith Corp success story?", "marketing"),
    ("Product naming discussion", "We need to finalize the name for the new feature.", "marketing"),
    ("Webinar planning", "Let's plan a webinar on industry trends for next month.", "marketing"),
    ("Blog post review", "Please review the attached blog post before publishing.", "marketing"),
    ("Competitive analysis", "Can you provide an analysis of competitor marketing?", "marketing"),
    ("SEO recommendations", "We need SEO improvements for better search rankings.", "marketing"),
    ("Video production request", "We need a product demo video for the website.", "marketing"),
    ("Event sponsorship opportunity", "Should we sponsor the tech conference in March?", "marketing"),
    ("Customer testimonial request", "Can you reach out to happy customers for testimonials?", "marketing"),
    ("Market research findings", "Here are the results from the recent market survey.", "marketing"),
    ("Brand ambassador program", "Let's discuss launching an influencer partnership program.", "marketing"),
    ("Rebranding proposal", "Here's the proposal for refreshing our brand identity.", "marketing"),
    ("Media kit request", "A journalist needs our media kit for an article.", "marketing"),
    ("Product launch timeline", "What's the marketing timeline for the spring launch?", "marketing"),
    ("Ad creative feedback", "Please review the new ad designs and provide feedback.", "marketing"),
    ("Content calendar update", "The content calendar needs updating for holidays.", "marketing"),
    ("Crisis communication plan", "We need a communication plan for the PR situation.", "marketing"),
    ("Lead generation report", "Here's the monthly lead gen performance report.", "marketing"),
    ("Partnership marketing", "Let's discuss co-marketing opportunities with partners.", "marketing"),
    ("Analytics dashboard review", "The marketing analytics dashboard needs attention.", "marketing"),
    ("Email automation setup", "We need to set up automated email sequences.", "marketing"),
    
    # ==================== CUSTOMER SERVICE (50+ examples) ====================
    ("Product not working", "The product I received doesn't turn on. Very disappointed.", "customer_service"),
    ("Refund request", "I'd like a refund for my recent purchase. Order #12345.", "customer_service"),
    ("Shipping delay complaint", "My order was supposed to arrive 5 days ago.", "customer_service"),
    ("Wrong item received", "I ordered the blue version but received red instead.", "customer_service"),
    ("Damaged product", "The item arrived broken. Please see attached photos.", "customer_service"),
    ("Cancel my subscription", "I want to cancel my subscription immediately.", "customer_service"),
    ("Poor customer service experience", "I've been on hold for 2 hours trying to get help.", "customer_service"),
    ("Product quality complaint", "The quality is much worse than described on the website.", "customer_service"),
    ("Missing parts", "The assembly kit is missing several important pieces.", "customer_service"),
    ("Warranty claim", "My product broke within the warranty period. How do I claim?", "customer_service"),
    ("Exchange request", "I'd like to exchange this for a different size.", "customer_service"),
    ("Billing complaint", "I was charged twice for the same order.", "customer_service"),
    ("Account cancellation", "Please delete my account and all associated data.", "customer_service"),
    ("Service outage complaint", "Your service has been down for 3 days. This is unacceptable.", "customer_service"),
    ("Late delivery", "Delivery was scheduled for Monday but it's now Wednesday.", "customer_service"),
    ("Product recall inquiry", "I heard there's a recall. Is my product affected?", "customer_service"),
    ("Feature not working", "The main feature that I bought this for doesn't work.", "customer_service"),
    ("Terrible experience", "Worst customer experience I've ever had. I want a manager.", "customer_service"),
    ("Return shipping label", "I need a prepaid return shipping label.", "customer_service"),
    ("Order tracking issue", "The tracking number you provided doesn't work.", "customer_service"),
    ("Subscription not cancelled", "I cancelled last month but was still charged.", "customer_service"),
    ("Product recall", "How do I return my product that was recalled?", "customer_service"),
    ("Misleading advertising", "The product is nothing like the advertisement showed.", "customer_service"),
    ("Unresponsive support", "I've sent 5 emails and no one has responded.", "customer_service"),
    ("App crashing", "Your mobile app keeps crashing. Please fix this.", "customer_service"),
    ("Request for credit", "I'd like a credit for the inconvenience caused.", "customer_service"),
    ("Delivery instructions ignored", "The driver left the package in the rain despite instructions.", "customer_service"),
    ("Service complaint", "Your technician was rude and unprofessional.", "customer_service"),
    ("Feature suggestion", "It would be great if your product could do X.", "customer_service"),
    ("Positive feedback", "Just wanted to say your support team was amazing!", "customer_service"),
    
    # ==================== OPERATIONS (50+ examples) ====================
    ("Shipment tracking", "Can you provide the tracking number for order #7890?", "operations"),
    ("Delivery schedule", "When is the expected delivery date for our equipment?", "operations"),
    ("Warehouse inventory question", "What's the current stock level of SKU-12345?", "operations"),
    ("Vendor delivery delay", "Our supplier says delivery will be delayed by 2 weeks.", "operations"),
    ("Quality control issue", "We found defects in 5% of the last shipment.", "operations"),
    ("Shipping rate inquiry", "What are shipping costs for international orders?", "operations"),
    ("Fulfillment center issue", "Orders from the West Coast center are delayed.", "operations"),
    ("Inventory replenishment", "We're running low on product X. Please reorder.", "operations"),
    ("Supply chain disruption", "Our main supplier has capacity issues.", "operations"),
    ("Packaging requirements", "What are the packaging specs for fragile items?", "operations"),
    ("Return merchandise authorization", "We need an RMA for defective products.", "operations"),
    ("Carrier change request", "Can we switch from FedEx to UPS for this account?", "operations"),
    ("Warehouse space needed", "We need additional storage space for the holiday season.", "operations"),
    ("Production schedule update", "Here's the updated production schedule for Q1.", "operations"),
    ("Equipment maintenance", "The conveyor belt in warehouse B needs maintenance.", "operations"),
    ("Customs clearance issue", "The international shipment is stuck in customs.", "operations"),
    ("Freight cost optimization", "Can we consolidate shipments to reduce costs?", "operations"),
    ("Product recall logistics", "How do we handle the logistics for the product recall?", "operations"),
    ("New vendor onboarding", "We need to onboard a new parts supplier.", "operations"),
    ("Safety incident report", "There was a minor accident in the warehouse today.", "operations"),
    ("Fleet management update", "Three delivery trucks need service this week.", "operations"),
    ("Capacity planning", "What's our production capacity for next quarter?", "operations"),
    ("Order fulfillment delay", "Several orders are delayed due to stock shortage.", "operations"),
    ("Supplier quality audit", "We need to schedule a quality audit at the supplier.", "operations"),
    ("Logistics cost report", "Here's the monthly logistics cost analysis.", "operations"),
    ("Cold chain compliance", "Are we meeting cold chain requirements for pharma?", "operations"),
    ("Drop shipping setup", "We want to set up drop shipping for new products.", "operations"),
    ("Import documentation", "What documents are needed for importing from China?", "operations"),
    ("Last mile delivery issue", "Last mile delivery costs are too high in rural areas.", "operations"),
    ("Inventory cycle count", "We need to schedule the quarterly inventory count.", "operations"),
    
    # ==================== EXECUTIVE (40+ examples) ====================
    ("Board meeting agenda", "Attached is the agenda for next week's board meeting.", "executive"),
    ("Investor update", "Please review the quarterly investor update letter.", "executive"),
    ("Strategic planning session", "We need to schedule the annual strategy retreat.", "executive"),
    ("M&A opportunity", "A potential acquisition target has been identified.", "executive"),
    ("CEO communication", "Please review this communication before it goes to all staff.", "executive"),
    ("Executive compensation review", "It's time for the annual executive comp review.", "executive"),
    ("Board resolution required", "We need board approval for the new credit facility.", "executive"),
    ("Shareholder meeting", "Preparing materials for the annual shareholder meeting.", "executive"),
    ("Leadership team changes", "Announcing changes to the executive leadership team.", "executive"),
    ("Company valuation", "Investment bankers provided preliminary valuation estimates.", "executive"),
    ("Confidential strategic matter", "This requires executive-level discussion only.", "executive"),
    ("IPO preparation", "Here's the timeline for IPO readiness activities.", "executive"),
    ("Private equity inquiry", "A PE firm has expressed interest in our company.", "executive"),
    ("Executive search", "We're starting the search for a new CFO.", "executive"),
    ("Crisis management", "We have a situation that requires immediate executive attention.", "executive"),
    ("Quarterly earnings call", "Preparing for the upcoming earnings call.", "executive"),
    ("Competitive intelligence", "Important competitive intelligence for leadership review.", "executive"),
    ("Board member communication", "A board member is requesting a call with the CEO.", "executive"),
    ("Strategic partnership", "A major strategic partnership opportunity has emerged.", "executive"),
    ("Succession planning", "We need to discuss executive succession planning.", "executive"),
    ("Regulatory meeting", "Meeting scheduled with regulatory officials.", "executive"),
    ("Media interview request", "Bloomberg wants to interview the CEO.", "executive"),
    ("Organizational restructuring", "Proposal for organizational changes attached.", "executive"),
    ("Executive offsite", "Planning the Q2 executive leadership offsite.", "executive"),
    ("Investor relations update", "Major institutional investor wants a call.", "executive"),
    ("Proxy statement review", "Please review the proxy statement draft.", "executive"),
    ("Governance committee", "Governance committee meeting scheduled for Thursday.", "executive"),
    ("Executive summary request", "The board needs an executive summary of the project.", "executive"),
    ("Confidential: Market opportunity", "Highly confidential market expansion opportunity.", "executive"),
    ("CEO succession", "Discussing long-term CEO succession plan.", "executive"),
    
    # ==================== GENERAL (30+ examples) ====================
    ("Office supplies order", "We need to reorder pens, paper, and sticky notes.", "general"),
    ("Meeting room booking", "Can I reserve Conference Room A for Thursday at 2pm?", "general"),
    ("Building maintenance", "The air conditioning on floor 3 isn't working.", "general"),
    ("Parking inquiry", "How do I get a parking permit for the garage?", "general"),
    ("Lost and found", "I left my jacket in the break room. Has anyone seen it?", "general"),
    ("Newsletter subscription", "Please subscribe me to the company newsletter.", "general"),
    ("General question", "Quick question - what are the office hours during holidays?", "general"),
    ("Cafeteria feedback", "The cafeteria should offer more vegetarian options.", "general"),
    ("Mail distribution", "I'm expecting an important package. When does mail arrive?", "general"),
    ("Visitor registration", "I have a guest visiting tomorrow. How do I register them?", "general"),
    ("Office event", "Don't forget about the team lunch this Friday!", "general"),
    ("Badge access", "My badge isn't working at the main entrance.", "general"),
    ("Contact information update", "Please update my phone number in the directory.", "general"),
    ("Weather closure question", "Is the office closed due to the snow storm?", "general"),
    ("Team building event", "Who's organizing the summer team building event?", "general"),
    ("Office plants", "Who is responsible for watering the office plants?", "general"),
    ("Birthday celebration", "We're celebrating Sarah's birthday in the break room.", "general"),
    ("Carpool interest", "Anyone interested in carpooling from the north side?", "general"),
    ("Office temperature", "It's too cold in the office. Can we adjust the thermostat?", "general"),
    ("Charity drive", "Reminder: the food drive ends this Friday.", "general"),
    ("Kitchen cleanliness", "Please clean up after using the kitchen.", "general"),
    ("Desk assignment", "I'm moving to the 4th floor. How do I arrange that?", "general"),
    ("Company swag", "Are there any company t-shirts available?", "general"),
    ("Phone extension", "What's the extension for the IT help desk?", "general"),
    ("Out of office setup", "How do I set up an out of office auto-reply?", "general"),
    ("Coffee machine broken", "The coffee machine on floor 2 is broken.", "general"),
    ("Elevator not working", "The west elevator is out of service again.", "general"),
    ("Fire drill notice", "Fire drill scheduled for tomorrow at 10am.", "general"),
    ("Survey reminder", "Please complete the employee engagement survey.", "general"),
    ("Holiday party", "RSVP for the holiday party by end of week.", "general"),
]


def get_training_data():
    """Return the training dataset"""
    return ENTERPRISE_TRAINING_DATA


def get_training_data_by_department():
    """Return training data organized by department"""
    by_dept = {}
    for subject, body, dept in ENTERPRISE_TRAINING_DATA:
        if dept not in by_dept:
            by_dept[dept] = []
        by_dept[dept].append({"subject": subject, "body": body})
    return by_dept


def get_training_stats():
    """Get statistics about the training data"""
    by_dept = {}
    for _, _, dept in ENTERPRISE_TRAINING_DATA:
        by_dept[dept] = by_dept.get(dept, 0) + 1
    
    return {
        "total_examples": len(ENTERPRISE_TRAINING_DATA),
        "by_department": by_dept
    }


if __name__ == "__main__":
    stats = get_training_stats()
    print(f"Total training examples: {stats['total_examples']}")
    print("\nBy department:")
    for dept, count in sorted(stats['by_department'].items(), key=lambda x: -x[1]):
        print(f"  {dept}: {count}")
